# Form implementation generated from reading ui file 'Converter.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(446, 341)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.SourcePath_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.SourcePath_Button.setObjectName("SourcePath_Button")
        self.gridLayout.addWidget(self.SourcePath_Button, 0, 0, 1, 1)
        self.SourcePath_lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.SourcePath_lineEdit.setDragEnabled(True)
        self.SourcePath_lineEdit.setReadOnly(True)
        self.SourcePath_lineEdit.setClearButtonEnabled(False)
        self.SourcePath_lineEdit.setObjectName("SourcePath_lineEdit")
        self.gridLayout.addWidget(self.SourcePath_lineEdit, 0, 1, 1, 1)
        self.DestinationPath_Button = QtWidgets.QPushButton(parent=self.groupBox)
        self.DestinationPath_Button.setObjectName("DestinationPath_Button")
        self.gridLayout.addWidget(self.DestinationPath_Button, 1, 0, 1, 1)
        self.DestinationPath_lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.DestinationPath_lineEdit.setDragEnabled(True)
        self.DestinationPath_lineEdit.setReadOnly(True)
        self.DestinationPath_lineEdit.setClearButtonEnabled(False)
        self.DestinationPath_lineEdit.setObjectName("DestinationPath_lineEdit")
        self.gridLayout.addWidget(self.DestinationPath_lineEdit, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)
        self.AIServer_lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.AIServer_lineEdit.setObjectName("AIServer_lineEdit")
        self.gridLayout_2.addWidget(self.AIServer_lineEdit, 1, 0, 1, 3)
        self.Status_textBrowser = QtWidgets.QTextBrowser(parent=Form)
        self.Status_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.Status_textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.Status_textBrowser.setObjectName("Status_textBrowser")
        self.gridLayout_2.addWidget(self.Status_textBrowser, 2, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(251, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.Start_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Start_pushButton.setMaximumSize(QtCore.QSize(81, 30))
        self.Start_pushButton.setObjectName("Start_pushButton")
        self.gridLayout_2.addWidget(self.Start_pushButton, 3, 1, 1, 1)
        self.Cancel_pushButton = QtWidgets.QPushButton(parent=Form)
        self.Cancel_pushButton.setMinimumSize(QtCore.QSize(81, 30))
        self.Cancel_pushButton.setMaximumSize(QtCore.QSize(81, 30))
        self.Cancel_pushButton.setObjectName("Cancel_pushButton")
        self.gridLayout_2.addWidget(self.Cancel_pushButton, 3, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "2.5D Converter"))
        self.groupBox.setTitle(_translate("Form", "Image Convertion"))
        self.SourcePath_Button.setText(_translate("Form", "Source Path"))
        self.SourcePath_lineEdit.setPlaceholderText(_translate("Form", "Image Source Path"))
        self.DestinationPath_Button.setText(_translate("Form", "Output Path"))
        self.DestinationPath_lineEdit.setPlaceholderText(_translate("Form", "Image Destination Path"))
        self.AIServer_lineEdit.setPlaceholderText(_translate("Form", "AI Server URL"))
        self.Status_textBrowser.setPlaceholderText(_translate("Form", "Example URL: http://ai.server.com:8080/analyze"))
        self.Start_pushButton.setText(_translate("Form", "Start"))
        self.Cancel_pushButton.setText(_translate("Form", "Cancel"))
