# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.DockOption.AllowNestedDocks|QtWidgets.QMainWindow.DockOption.AllowTabbedDocks|QtWidgets.QMainWindow.DockOption.AnimatedDocks|QtWidgets.QMainWindow.DockOption.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.axial_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.axial_widget.setObjectName("axial_widget")
        self.gridLayout.addWidget(self.axial_widget, 0, 0, 1, 1)
        self.sagittal_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.sagittal_widget.setObjectName("sagittal_widget")
        self.gridLayout.addWidget(self.sagittal_widget, 0, 1, 1, 1)
        self.coronal_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.coronal_widget.setObjectName("coronal_widget")
        self.gridLayout.addWidget(self.coronal_widget, 1, 0, 1, 1)
        self.d3_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.d3_widget.setObjectName("d3_widget")
        self.gridLayout.addWidget(self.d3_widget, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.MainBar = QtWidgets.QDockWidget(parent=MainWindow)
        self.MainBar.setEnabled(True)
        self.MainBar.setMinimumSize(QtCore.QSize(200, 100))
        self.MainBar.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self.MainBar.setWindowTitle("")
        self.MainBar.setObjectName("MainBar")
        self.dockWidgetContents_9 = QtWidgets.QWidget()
        self.dockWidgetContents_9.setObjectName("dockWidgetContents_9")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dockWidgetContents_9)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.dockWidgetContents_9)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_3.addWidget(self.textEdit, 0, 0, 1, 1)
        self.MainBar.setWidget(self.dockWidgetContents_9)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.MainBar)
        self.MainTool = QtWidgets.QDockWidget(parent=MainWindow)
        self.MainTool.setMinimumSize(QtCore.QSize(200, 100))
        self.MainTool.setFeatures(QtWidgets.QDockWidget.DockWidgetFeature.NoDockWidgetFeatures)
        self.MainTool.setAllowedAreas(QtCore.Qt.DockWidgetArea.LeftDockWidgetArea)
        self.MainTool.setObjectName("MainTool")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.MainTool.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.MainTool)
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionRotate = QtGui.QAction(parent=MainWindow)
        self.actionRotate.setObjectName("actionRotate")
        self.actionImage_Information = QtGui.QAction(parent=MainWindow)
        self.actionImage_Information.setObjectName("actionImage_Information")
        self.actionEncrypt_Image = QtGui.QAction(parent=MainWindow)
        self.actionEncrypt_Image.setObjectName("actionEncrypt_Image")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen_Image = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Image.setObjectName("actionOpen_Image")
        self.actionImage_Converter = QtGui.QAction(parent=MainWindow)
        self.actionImage_Converter.setObjectName("actionImage_Converter")
        self.menuFile.addAction(self.actionOpen_Image)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PySlicer"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">PySlicer</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:700;\">with</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Group 1</span></p></body></html>"))
        self.MainTool.setWindowTitle(_translate("MainWindow", "Main Tool"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionRotate.setText(_translate("MainWindow", "Rotate Image"))
        self.actionImage_Information.setText(_translate("MainWindow", "Image Information"))
        self.actionEncrypt_Image.setText(_translate("MainWindow", "Encrypt Image"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_Image.setText(_translate("MainWindow", "Open Image"))
        self.actionImage_Converter.setText(_translate("MainWindow", "Image Converter"))
